#lang racket/base

;; Epistemic State Vector
;; Package D: Observability layer
;; Implements KK/KU/UK/UU tensor (the core epistemic state)

(require "../kernel-spec.rkt")

(provide
 make-epistemic-vector)
;; Accessors are automatically generated by struct: Epistemic-Vector-kk, Epistemic-Vector-ku, etc.

;; Epistemic-Vector is already defined in kernel-spec.rkt
;; This module provides convenience constructors

;; Create epistemic vector from components
(define (make-epistemic-vector kk ku uk uu)
  "Create Epistemic-Vector from KK, KU, UK, UU components"
  (Epistemic-Vector kk ku uk uu))

;; Accessors are already provided by struct definition
;; But we can add convenience functions here if needed

